# Generated by Django 2.0.3 on 2018-04-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='totalHardness',
            field=models.FloatField(default=0.0),
        ),
    ]
